### ISSUE TITLE
How to solve it?

### ISSUE THREAD

**Issue by saffysgd** [Pix3lPirat3/mineprompt_rewritten#4]
Uncaught (in promise) Error: unsupported protocol version: 1.20.6
    at Object.createClient (C:\mineprompt_rewritten\node_modules\minecraft-protocol\src\createClient.js:30:22)
    at createBot (C:\mineprompt_rewritten\node_modules\mineflayer\lib\loader.js:95:35)
    at Object.startClient (ui-mineflayer.js:20:17)
    at Object.execute (VM1023 C:\mineprompt_rewritten\commands\global\connect.js:90:23)
    at ce.fn.init.onCommandSubmit (terminal.js:55:18)
    at s (jquery.terminal.min.js:46:124400)
    at ce.fn.init.me (jquery.terminal.min.js:46:125381)
    at Object.ENTER (jquery.terminal.min.js:46:45330)
    at HTMLHtmlElement.it (jquery.terminal.min.js:46:65025)
    at HTMLHtmlElement.dispatch (jquery.min.js:2:40035)

**Comment by OBNinjaa** [comment]
1.20.6 Isn't supported yet

**Comment by saffysgd** [comment]
> 1.20.6 Isn't supported yet

I'll try to install version 1.20.4.
